version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  flask-app:
    build: .
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/externalDB

volumes:
  mongodb_data:

